name: CI

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest 

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Install Postman CLI
        shell: powershell
        run: |
          [System.Net.ServicePointManager]::SecurityProtocol = 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMEN_KEY }}

      - name: Run API tests
        run: postman collection run "${{ github.workspace }}\postman\collections\One Hub.json" -e "44656000-fdc57671-4929-4dd5-9a10-8ccf9efd690d"
