name: CI

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Fetch Postman environment
        run: |
          curl "https://testapi.turkiyeshell.com/maincore/enviroment/44656000-fdc57671-4929-4dd5-9a10-8ccf9efd690d" `
          -H "X-Api-Key: ${{ secrets.POSTMEN_KEY }}" `
          -o environment.json

      - name: Install jq for Windows
        run: choco install jq -y

      - name: Transform Postman environment file
        run: jq ".environment" environment.json > environment_transformed.json

      - name: Debug - Show contents of environment file
        run: |
          echo "Contents of environment.json:"
          type environment.json

      - name: Install Postman CLI
        run: |
          powershell.exe -NoProfile -InputFormat None -ExecutionPolicy AllSigned `
            -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; `
            iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"

      - name: Debug - Check working directory files
        run: dir

      - name: Run API with Newman and generate HTMLExtra report
        run: |
          newman run "${{ github.workspace }}\\postman\\collections\\One Hub.json" `
          -e environment_transformed.json `
          --reporters cli,htmlextra `
          --reporter-htmlextra-export newman-report.html

      - name: Debug - List files in workspace
        run: dir

      - name: Upload HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: newman-report
          path: newman-report.html

          
